import { chromium } from 'playwright-core';
const EXE = 'C:/Users/Nicholas/AppData/Local/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe';
const PDF = 'C:/Users/Nicholas/Desktop/coding/paint-takeoff/friend-examples/2 Drawings - Architectural.pdf';
const browser = await chromium.launch({ executablePath: EXE });
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
page.on('console', (m) => { if (m.text().startsWith('[qa]')) console.log(m.text()); });
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message));
await page.goto('http://localhost:5199/', { waitUntil: 'networkidle' });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: 'networkidle' });
await page.setInputFiles('input[type=file]', PDF);
await page.waitForFunction(() => document.querySelector('.pdf-canvas')?.width > 400, null, { timeout: 60000 });
await page.fill('.page-input', '5');
await page.locator('.page-input').blur();
await page.waitForTimeout(1000);
await page.selectOption('.preset-select', '1:75');
await page.waitForSelector('.modal');
await page.getByRole('button', { name: 'Skip this' }).click();
await page.getByRole('button', { name: 'Quick Area' }).click();
await page.waitForTimeout(500);
await page.mouse.click(455, 535);
await page.waitForTimeout(4000);
console.log('toast:', await page.locator('.toast').textContent().catch(() => 'none'));
await page.waitForSelector('.qa-card', { timeout: 40000 });
await page.evaluate(() => {
  const c = window.__qaBarrier;
  const url = c.toDataURL('image/png');
  const a = document.createElement('a');
  a.href = url;
  a.download = 'barrier.png';
  a.click();
});
const download = await page.waitForEvent('download', { timeout: 10000 }).catch(() => null);
if (download) await download.saveAs('barrier-cleaned.png');
console.log('saved barrier-cleaned.png');
await browser.close();
