import { chromium } from 'playwright-core';
import { openPdf } from './helpers.mjs';
const EXE = 'C:/Users/Nicholas/AppData/Local/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe';
const PDF = 'C:/Users/Nicholas/Desktop/coding/paint-takeoff/friend-examples/2 Drawings - Architectural.pdf';
const browser = await chromium.launch({ executablePath: EXE });
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message));
await page.goto('http://localhost:5199/', { waitUntil: 'networkidle' });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: 'networkidle' });
await openPdf(page, PDF);
await page.getByRole('button', { name: 'Home', exact: true }).click();
await page.waitForSelector('.dash-card');
await page.locator('.dash-card').first().click();
await page.waitForSelector('.action-sheet');
await page.getByRole('button', { name: 'Go to quote' }).click();
await page.waitForSelector('.quote-modal');
console.log('quote open:', await page.locator('.quote-modal').count());
await page.evaluate(() => document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })));
await page.waitForTimeout(400);
console.log('quote after dispatched esc:', await page.locator('.quote-modal').count());
await page.keyboard.press('Escape');
await page.waitForTimeout(400);
console.log('quote after esc:', await page.locator('.quote-modal').count());
console.log('backdrops:', await page.locator('.modal-backdrop').count());
console.log('modals open:', await page.locator('.modal').count());
console.log('toolbar visible:', await page.locator('.toolbar').count());
await browser.close();
