import { chromium } from 'playwright-core';
const EXE = 'C:/Users/Nicholas/AppData/Local/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe';
const PDF = 'C:/Users/Nicholas/Desktop/coding/paint-takeoff/friend-examples/2 Drawings - Architectural.pdf';
const browser = await chromium.launch({ executablePath: EXE });
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
await page.goto('http://localhost:5199/', { waitUntil: 'networkidle' });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: 'networkidle' });
await page.setInputFiles('input[type=file]', PDF);
await page.waitForFunction(() => document.querySelector('.pdf-canvas')?.width > 400, null, { timeout: 60000 });
await page.fill('.page-input', '5');
await page.locator('.page-input').blur();
await page.waitForTimeout(1000);
await page.selectOption('.preset-select', '1:75');
await page.waitForSelector('.modal');
await page.getByRole('button', { name: 'Skip this' }).click();
await page.getByRole('button', { name: 'Measure', exact: true }).click();
await page.locator('.kind-picker button', { hasText: 'Ceiling' }).click();
const cbox = await page.locator('.pdf-canvas').boundingBox();
// trace the community-centre region area (relative coords from page5-fit)
await page.mouse.click(cbox.x + 155, cbox.y + 367);
await page.mouse.click(cbox.x + 293, cbox.y + 367);
await page.mouse.click(cbox.x + 293, cbox.y + 427);
await page.mouse.click(cbox.x + 155, cbox.y + 427);
await page.waitForTimeout(300);
await page.screenshot({ path: 'ceiling-polygon.png' });
await page.mouse.dblclick(cbox.x + 155, cbox.y + 427);
await page.waitForTimeout(400);
await page.getByRole('button', { name: /Measurements/ }).click();
await page.waitForSelector('.measure-panel');
await page.screenshot({ path: 'ceiling-polygon.png' });
console.log('saved ceiling-polygon.png');
await browser.close();
